version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: vvduth/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=vprodbpass
 
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
 
  vpromq01:
    image: rabbitmq
    ports: 
      - "5672:5672"
 
 
  vproapp:
    build: 
      context: ./Docker-files/app
    image: vvduth/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
 
  vproweb:
    build:
      context: ./Docker-files/web
    image: vvduth/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
 
volumes:
  vprodbdata: {}
  vproappdata: {}
